---
# aztest playbook, for installing OpenCloud

- hosts: head
  roles:
    - { role: common-prep, become: yes }
    - { role: head-prep, become: yes }
    - juju-user-prep
    - juju-setup

- hosts: compute
  become: yes
  roles:
    - { role: common-prep, become: yes }
    - { role: compute-prep, become: yes }

