---
# aztest playbook, for installing an OpenCloud site

- hosts: all
  tasks:
  - include_vars: vars/opencloud_defaults.yml
  - include_vars: vars/aztest.yml

# common setup
- hosts: all
  become: yes
  roles:
    - common-prep
    - dell-virt

# Install DNS servers on the head node
- hosts: head
  become: yes
  roles:
    - dns-nsd
    - dns-unbound

# Configure DNS serves on all 

- hosts: all
  become: yes
  roles:
    - dns-configure

# prepare the head node, install juju
- hosts: head
  roles:
    - { role: head-prep, become: yes }
    - juju-user-prep
    - juju-setup

# prepare the compute nodes
- hosts: compute
  become: yes
  roles:
    - compute-prep

# configure openstack on head node, including compute nodes
- hosts: head
  roles:
    - juju-openstack-config

