# Enable virtualization on Dell R410s
---
- hosts: all
  sudo: yes
  tasks:
  - name: Update files
    copy: src=files/etc/apt/sources.list.d/linux.dell.com.sources.list
      dest=/etc/apt/sources.list.d/linux.dell.com.sources.list

  - name: Add repo key
    apt_key: keyserver=pool.sks-keyservers.net
      id=1285491434D8786F
      state=present

  - name: Update apt cache
    apt: update_cache=yes

  - name: Install packages
    apt: name=dtk-scripts state=present

  - name: Enable virtualization in BIOS
    shell: /opt/dell/toolkit/bin/syscfg --virtualization=enable
