# Enable virtualization on Dell R410s
---
- hosts: node70.princeton.vicci.org
  sudo: yes
  tasks:
  - name: Remove old apt proxy config
    file: path=/etc/apt/apt.conf
     state=absent

  - name: Update files
    copy: src=files/etc/apt/sources.list.d/linux.dell.com.sources.list
      dest=/etc/apt/sources.list.d/linux.dell.com.sources.list

  - shell: gpg --keyserver pool.sks-keyservers.net --recv-key 1285491434D8786F

  - shell: gpg -a --export 1285491434D8786F | sudo apt-key add -

  - name: Update apt cache
    apt: upgrade=yes update_cache=yes

  - name: Install packages
    apt: name=dtk-scripts state=present

  - name: Enable virtualization in BIOS
    shell: /opt/dell/toolkit/bin/syscfg --virtualization=enable
