---
# roles/juju-user-prep/main/tasks.yml

- name: Disable host key checking in ~/.ssh/config
  lineinfile:
    dest={{ ansible_user_dir }}/.ssh/config
    line="StrictHostKeyChecking no"
    create=yes
    mode=0600

- name: Disable host key checking in ~/.ansible.cfg
  copy:
    src=ansible.cfg
    dest={{ ansible_user_dir }}/.ansible.cfg

