---
# roles/juju-setup/main/tasks.yml

- name: Verify that we can log into every VM
  command: ansible services -m ping -u ubuntu

- name: Initialize Juju
  command: juju generate-config
    creates={{ ansible_user_dir }}/.juju/environments.yaml

- name: Create Juju config file from template
  template:
    src=environments.yaml.j2
    dest={{ ansible_user_dir }}/.juju/environments.yaml

- name: Bootstrap Juju
  command: juju bootstrap
    creates={{ ansible_user_dir }}/.juju/environments/manual.jenv

- name: Copy openstack.cfg for Juju
  become: yes
  copy:
    src=openstack.cfg
    dest=/usr/local/src/openstack.cfg

# Code for juju_facts this is in library/juju_facts.py

- name: Obtain Juju Facts
  juju_facts:

# For setwise operations on desired vs Juju state:
# list of VM names head_vm_list dict: head_vm_list | map(attribute='name') | list
# list of active juju_machines names: juju_machines.keys()
# list of active juju_services names: juju_services.keys()

- name: Add machines to Juju
  command: "juju add-machine ssh:{{ item }}"
  with_items: "{{ head_vm_list | map(attribute='name') | list | difference( juju_machines.keys()) }}"

