---
# file: roles/common-prep/tasks/main.yml

- name: Upgrade system to current using apt
  apt: update_cache=yes upgrade=dist
  notify:
    - restart machine
    - wait for machine

- name: Install standard packages
  apt:  pkg={{ item }} state=present
  with_items:
   - tmux
   - vim

- name: Enable vim syntax highlighting
  lineinfile: dest=/etc/vim/vimrc
    regexp="^\s*syntax on"
    line="syntax on"

